#!/usr/bin/env bash

guard() {
    if [ -z "$1" ]; then
	echo "$2"
	exit
    fi
}

cmd=$1
guard "$cmd" "command not specified"

BAK=$HOME/backups
STAMPED_NAME="$BAK/$(iso-date)"

items="
.viminfo
.vimrc
.tmux.conf
.prettierrc.yaml
.npmignore
.gitignore
Documents"

case $cmd in
    store)
	mkdir -p $STAMPED_NAME
	for item in $items; do
	    cp -rv ~/$item $STAMPED_NAME
	done
	;;

    restore)
	for item in $items; do
	    cp -rv $LATEST/$item ~
	done
	;;

    *)
	echo "unknown command"
esac
