#!/usr/bin/env bash

guard() {
    if [ -z "$1" ]; then
	echo "$2"
	exit
    fi
}

cmd=$1
guard "$cmd" "command not specified"

BAK=$HOME/backups
LATEST=$BAK/latest
NEW_NAME="$BAK/before-$(iso-date)"

items="
.viminfo
.vimrc
.tmux.conf
.prettierrc.yaml
.npmignore
.gitignore
Documents"

case $cmd in
    store)
	mv $LATEST $NEW_NAME

	mkdir -p $LATEST
	for item in $items; do
	    cp -rv ~/$item $LATEST
	done
	;;

    restore)
	for item in $items; do
	    cp -rv $LATEST/$item ~
	done
	;;

    *)
	echo "unknown command"
esac
