#!/usr/bin/env bash

guard() {
    if [ -z "$1" ]; then
	echo "$2"
	exit
    fi
}

### 0
tmux-session 0 $CODE

### CODE
for main_folder in $(ls $CODE); do
    tmux-session $main_folder \
	$CODE/$main_folder \
	$CODE/$main_folder/*
    done

### MAIN
tmux-session 01-MAIN \
    $FILES \
    $REPO \
    $SCRIPTS \
    $ASSETS

tmux-session 02-ADMIN \
    $ADMIN \
    $ADMIN/*

### FINISH
cd
tmux attach -t 01-MAIN
