#!/usr/bin/env bash

guard() {
    if [ -z "$1" ]; then
	echo "$2"
	exit
    fi
}

### 0
tmux-session 0 $CODE

### CODE
for main_folder in $(ls $CODE); do
    tmux-session $main_folder \
	$CODE/$main_folder \
	$CODE/$main_folder/*
    done

### LOCAL
for main_folder in $(ls $ADMIN); do
    tmux-session $MAIN_folder \
	$ADMIN/$main_folder
    done

### MAIN
tmux-session 01-MAIN \
    $REPO \
    $SCRIPTS \
    $ASSETS

### FINISH
cd
tmux attach -t 01-MAIN
